apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "argo-ci.labels" . | nindent 4 }}
    {{- with .Values.role.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.role.rules | nindent 2 }}
